apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: github-secrets-reader
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-secrets-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: github-secrets-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: actions
